// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/sync/v2/sync_v2.proto

package syncproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataKind int32

const (
	DataKind_DATA_KIND_UNSPECIFIED DataKind = 0
	DataKind_DATA_KIND_NORMAL      DataKind = 1
	DataKind_DATA_KIND_GPIO        DataKind = 2
)

// Enum value maps for DataKind.
var (
	DataKind_name = map[int32]string{
		0: "DATA_KIND_UNSPECIFIED",
		1: "DATA_KIND_NORMAL",
		2: "DATA_KIND_GPIO",
	}
	DataKind_value = map[string]int32{
		"DATA_KIND_UNSPECIFIED": 0,
		"DATA_KIND_NORMAL":      1,
		"DATA_KIND_GPIO":        2,
	}
)

func (x DataKind) Enum() *DataKind {
	p := new(DataKind)
	*p = x
	return p
}

func (x DataKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sync_v2_sync_v2_proto_enumTypes[0].Descriptor()
}

func (DataKind) Type() protoreflect.EnumType {
	return &file_proto_sync_v2_sync_v2_proto_enumTypes[0]
}

func (x DataKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataKind.Descriptor instead.
func (DataKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{0}
}

type ClientHello struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StationIdentifier string                 `protobuf:"bytes,1,opt,name=station_identifier,json=stationIdentifier,proto3" json:"station_identifier,omitempty"`
	ProtocolVersion   string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetStationIdentifier() string {
	if x != nil {
		return x.StationIdentifier
	}
	return ""
}

func (x *ClientHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type ServerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{1}
}

func (x *ServerHello) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

type DeviceItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]string      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map[item_type]item_name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceItems) Reset() {
	*x = DeviceItems{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceItems) ProtoMessage() {}

func (x *DeviceItems) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceItems.ProtoReflect.Descriptor instead.
func (*DeviceItems) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceItems) GetItems() map[string]string {
	if x != nil {
		return x.Items
	}
	return nil
}

type StationInfo struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Identifier    string                  `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Devices       map[string]*DeviceItems `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map[device_name]items
	Cameras       []string                `protobuf:"bytes,3,rep,name=cameras,proto3" json:"cameras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StationInfo) Reset() {
	*x = StationInfo{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationInfo) ProtoMessage() {}

func (x *StationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationInfo.ProtoReflect.Descriptor instead.
func (*StationInfo) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{3}
}

func (x *StationInfo) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *StationInfo) GetDevices() map[string]*DeviceItems {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *StationInfo) GetCameras() []string {
	if x != nil {
		return x.Cameras
	}
	return nil
}

type ItemsLatest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatestUnixMs  map[string]int64       `protobuf:"bytes,1,rep,name=latest_unix_ms,json=latestUnixMs,proto3" json:"latest_unix_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // map[item_name]latest_msec
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemsLatest) Reset() {
	*x = ItemsLatest{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemsLatest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsLatest) ProtoMessage() {}

func (x *ItemsLatest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsLatest.ProtoReflect.Descriptor instead.
func (*ItemsLatest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{4}
}

func (x *ItemsLatest) GetLatestUnixMs() map[string]int64 {
	if x != nil {
		return x.LatestUnixMs
	}
	return nil
}

type StatusLatest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatestRowId   int64                  `protobuf:"varint,1,opt,name=latest_row_id,json=latestRowId,proto3" json:"latest_row_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusLatest) Reset() {
	*x = StatusLatest{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusLatest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusLatest) ProtoMessage() {}

func (x *StatusLatest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusLatest.ProtoReflect.Descriptor instead.
func (*StatusLatest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{5}
}

func (x *StatusLatest) GetLatestRowId() int64 {
	if x != nil {
		return x.LatestRowId
	}
	return 0
}

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	UnixMs        int64                  `protobuf:"varint,3,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	Kind          DataKind               `protobuf:"varint,4,opt,name=kind,proto3,enum=tide.sync.v2.DataKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{6}
}

func (x *DataPoint) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DataPoint) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

func (x *DataPoint) GetKind() DataKind {
	if x != nil {
		return x.Kind
	}
	return DataKind_DATA_KIND_UNSPECIFIED
}

type DataBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	Points        []*DataPoint           `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBatch) Reset() {
	*x = DataBatch{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBatch) ProtoMessage() {}

func (x *DataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBatch.ProtoReflect.Descriptor instead.
func (*DataBatch) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{7}
}

func (x *DataBatch) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *DataBatch) GetPoints() []*DataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type ItemStatusLog struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RowId           int64                  `protobuf:"varint,1,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	ItemName        string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ChangedAtUnixMs int64                  `protobuf:"varint,4,opt,name=changed_at_unix_ms,json=changedAtUnixMs,proto3" json:"changed_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ItemStatusLog) Reset() {
	*x = ItemStatusLog{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStatusLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStatusLog) ProtoMessage() {}

func (x *ItemStatusLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStatusLog.ProtoReflect.Descriptor instead.
func (*ItemStatusLog) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{8}
}

func (x *ItemStatusLog) GetRowId() int64 {
	if x != nil {
		return x.RowId
	}
	return 0
}

func (x *ItemStatusLog) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ItemStatusLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ItemStatusLog) GetChangedAtUnixMs() int64 {
	if x != nil {
		return x.ChangedAtUnixMs
	}
	return 0
}

type ItemStatusBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	Logs          []*ItemStatusLog       `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStatusBatch) Reset() {
	*x = ItemStatusBatch{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStatusBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStatusBatch) ProtoMessage() {}

func (x *ItemStatusBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStatusBatch.ProtoReflect.Descriptor instead.
func (*ItemStatusBatch) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{9}
}

func (x *ItemStatusBatch) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *ItemStatusBatch) GetLogs() []*ItemStatusLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type RpiStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuTemp       float64                `protobuf:"fixed64,1,opt,name=cpu_temp,json=cpuTemp,proto3" json:"cpu_temp,omitempty"`
	UnixMs        int64                  `protobuf:"varint,2,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpiStatus) Reset() {
	*x = RpiStatus{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpiStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpiStatus) ProtoMessage() {}

func (x *RpiStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpiStatus.ProtoReflect.Descriptor instead.
func (*RpiStatus) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{10}
}

func (x *RpiStatus) GetCpuTemp() float64 {
	if x != nil {
		return x.CpuTemp
	}
	return 0
}

func (x *RpiStatus) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

type CameraSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraName    string                 `protobuf:"bytes,1,opt,name=camera_name,json=cameraName,proto3" json:"camera_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraSnapshotRequest) Reset() {
	*x = CameraSnapshotRequest{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraSnapshotRequest) ProtoMessage() {}

func (x *CameraSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CameraSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{11}
}

func (x *CameraSnapshotRequest) GetCameraName() string {
	if x != nil {
		return x.CameraName
	}
	return ""
}

type CameraSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraSnapshotResponse) Reset() {
	*x = CameraSnapshotResponse{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraSnapshotResponse) ProtoMessage() {}

func (x *CameraSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CameraSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{12}
}

func (x *CameraSnapshotResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CameraSnapshotResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ErrorFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorFrame) Reset() {
	*x = ErrorFrame{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorFrame) ProtoMessage() {}

func (x *ErrorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorFrame.ProtoReflect.Descriptor instead.
func (*ErrorFrame) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{13}
}

func (x *ErrorFrame) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorFrame) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorFrame) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type StationMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*StationMessage_ClientHello
	//	*StationMessage_ServerHello
	//	*StationMessage_StationInfo
	//	*StationMessage_ItemsLatest
	//	*StationMessage_StatusLatest
	//	*StationMessage_DataBatch
	//	*StationMessage_ItemStatusBatch
	//	*StationMessage_RpiStatus
	//	*StationMessage_CameraSnapshotRequest
	//	*StationMessage_CameraSnapshotResponse
	//	*StationMessage_Error
	Body          isStationMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StationMessage) Reset() {
	*x = StationMessage{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationMessage) ProtoMessage() {}

func (x *StationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationMessage.ProtoReflect.Descriptor instead.
func (*StationMessage) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{14}
}

func (x *StationMessage) GetBody() isStationMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *StationMessage) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Body.(*StationMessage_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *StationMessage) GetServerHello() *ServerHello {
	if x != nil {
		if x, ok := x.Body.(*StationMessage_ServerHello); ok {
			return x.ServerHello
		}
	}
	return nil
}

func (x *StationMessage) GetStationInfo() *StationInfo {
	if x != nil {
		if x, ok := x.Body.(*StationMessage_StationInfo); ok {
			return x.StationInfo
		}
	}
	return nil
}

func (x *StationMessage) GetItemsLatest() *ItemsLatest {
	if x != nil {
		if x, ok := x.Body.(*StationMessage_ItemsLatest); ok {
			return x.ItemsLatest
		}
	}
	return nil
}

func (x *StationMessage) GetStatusLatest() *StatusLatest {
	if x != nil {
		if x, ok := x.Body.(*StationMessage_StatusLatest); ok {
			return x.StatusLatest
		}
	}
	return nil
}

func (x *StationMessage) GetDataBatch() *DataBatch {
	if x != nil {
		if x, ok := x.Body.(*StationMessage_DataBatch); ok {
			return x.DataBatch
		}
	}
	return nil
}

func (x *StationMessage) GetItemStatusBatch() *ItemStatusBatch {
	if x != nil {
		if x, ok := x.Body.(*StationMessage_ItemStatusBatch); ok {
			return x.ItemStatusBatch
		}
	}
	return nil
}

func (x *StationMessage) GetRpiStatus() *RpiStatus {
	if x != nil {
		if x, ok := x.Body.(*StationMessage_RpiStatus); ok {
			return x.RpiStatus
		}
	}
	return nil
}

func (x *StationMessage) GetCameraSnapshotRequest() *CameraSnapshotRequest {
	if x != nil {
		if x, ok := x.Body.(*StationMessage_CameraSnapshotRequest); ok {
			return x.CameraSnapshotRequest
		}
	}
	return nil
}

func (x *StationMessage) GetCameraSnapshotResponse() *CameraSnapshotResponse {
	if x != nil {
		if x, ok := x.Body.(*StationMessage_CameraSnapshotResponse); ok {
			return x.CameraSnapshotResponse
		}
	}
	return nil
}

func (x *StationMessage) GetError() *ErrorFrame {
	if x != nil {
		if x, ok := x.Body.(*StationMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStationMessage_Body interface {
	isStationMessage_Body()
}

type StationMessage_ClientHello struct {
	ClientHello *ClientHello `protobuf:"bytes,1,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type StationMessage_ServerHello struct {
	ServerHello *ServerHello `protobuf:"bytes,2,opt,name=server_hello,json=serverHello,proto3,oneof"`
}

type StationMessage_StationInfo struct {
	StationInfo *StationInfo `protobuf:"bytes,3,opt,name=station_info,json=stationInfo,proto3,oneof"`
}

type StationMessage_ItemsLatest struct {
	ItemsLatest *ItemsLatest `protobuf:"bytes,4,opt,name=items_latest,json=itemsLatest,proto3,oneof"`
}

type StationMessage_StatusLatest struct {
	StatusLatest *StatusLatest `protobuf:"bytes,5,opt,name=status_latest,json=statusLatest,proto3,oneof"`
}

type StationMessage_DataBatch struct {
	DataBatch *DataBatch `protobuf:"bytes,6,opt,name=data_batch,json=dataBatch,proto3,oneof"`
}

type StationMessage_ItemStatusBatch struct {
	ItemStatusBatch *ItemStatusBatch `protobuf:"bytes,7,opt,name=item_status_batch,json=itemStatusBatch,proto3,oneof"`
}

type StationMessage_RpiStatus struct {
	RpiStatus *RpiStatus `protobuf:"bytes,8,opt,name=rpi_status,json=rpiStatus,proto3,oneof"`
}

type StationMessage_CameraSnapshotRequest struct {
	CameraSnapshotRequest *CameraSnapshotRequest `protobuf:"bytes,9,opt,name=camera_snapshot_request,json=cameraSnapshotRequest,proto3,oneof"`
}

type StationMessage_CameraSnapshotResponse struct {
	CameraSnapshotResponse *CameraSnapshotResponse `protobuf:"bytes,10,opt,name=camera_snapshot_response,json=cameraSnapshotResponse,proto3,oneof"`
}

type StationMessage_Error struct {
	Error *ErrorFrame `protobuf:"bytes,11,opt,name=error,proto3,oneof"`
}

func (*StationMessage_ClientHello) isStationMessage_Body() {}

func (*StationMessage_ServerHello) isStationMessage_Body() {}

func (*StationMessage_StationInfo) isStationMessage_Body() {}

func (*StationMessage_ItemsLatest) isStationMessage_Body() {}

func (*StationMessage_StatusLatest) isStationMessage_Body() {}

func (*StationMessage_DataBatch) isStationMessage_Body() {}

func (*StationMessage_ItemStatusBatch) isStationMessage_Body() {}

func (*StationMessage_RpiStatus) isStationMessage_Body() {}

func (*StationMessage_CameraSnapshotRequest) isStationMessage_Body() {}

func (*StationMessage_CameraSnapshotResponse) isStationMessage_Body() {}

func (*StationMessage_Error) isStationMessage_Body() {}

// RelayDownstreamHello 下游 server 握手，告知自己的身份和认证信息。
type RelayDownstreamHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Username        string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                                      // 上游分配给下游的用户名
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // 协议版本，当前 "v2"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RelayDownstreamHello) Reset() {
	*x = RelayDownstreamHello{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayDownstreamHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayDownstreamHello) ProtoMessage() {}

func (x *RelayDownstreamHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayDownstreamHello.ProtoReflect.Descriptor instead.
func (*RelayDownstreamHello) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{15}
}

func (x *RelayDownstreamHello) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RelayDownstreamHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

// RelayUpstreamHello 上游 server 握手应答。
type RelayUpstreamHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayUpstreamHello) Reset() {
	*x = RelayUpstreamHello{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayUpstreamHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayUpstreamHello) ProtoMessage() {}

func (x *RelayUpstreamHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayUpstreamHello.ProtoReflect.Descriptor instead.
func (*RelayUpstreamHello) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{16}
}

func (x *RelayUpstreamHello) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

// RelayStationFull 上游发送的完整站点信息（含设备和 item 列表）。
// 用于全量配置同步阶段。
type RelayStationFull struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // station UUID
	Identifier        string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IpAddr            string                 `protobuf:"bytes,4,opt,name=ip_addr,json=ipAddr,proto3" json:"ip_addr,omitempty"`
	Location          []byte                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"` // JSON
	Partner           []byte                 `protobuf:"bytes,6,opt,name=partner,proto3" json:"partner,omitempty"`   // JSON
	Cameras           []byte                 `protobuf:"bytes,7,opt,name=cameras,proto3" json:"cameras,omitempty"`   // JSON
	Status            string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	StatusChangedAtMs int64                  `protobuf:"varint,9,opt,name=status_changed_at_ms,json=statusChangedAtMs,proto3" json:"status_changed_at_ms,omitempty"`
	Upstream          bool                   `protobuf:"varint,10,opt,name=upstream,proto3" json:"upstream,omitempty"`
	Devices           []*RelayDevice         `protobuf:"bytes,11,rep,name=devices,proto3" json:"devices,omitempty"`
	Items             []*RelayItem           `protobuf:"bytes,12,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RelayStationFull) Reset() {
	*x = RelayStationFull{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStationFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStationFull) ProtoMessage() {}

func (x *RelayStationFull) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStationFull.ProtoReflect.Descriptor instead.
func (*RelayStationFull) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{17}
}

func (x *RelayStationFull) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RelayStationFull) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *RelayStationFull) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RelayStationFull) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *RelayStationFull) GetLocation() []byte {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *RelayStationFull) GetPartner() []byte {
	if x != nil {
		return x.Partner
	}
	return nil
}

func (x *RelayStationFull) GetCameras() []byte {
	if x != nil {
		return x.Cameras
	}
	return nil
}

func (x *RelayStationFull) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RelayStationFull) GetStatusChangedAtMs() int64 {
	if x != nil {
		return x.StatusChangedAtMs
	}
	return 0
}

func (x *RelayStationFull) GetUpstream() bool {
	if x != nil {
		return x.Upstream
	}
	return false
}

func (x *RelayStationFull) GetDevices() []*RelayDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *RelayStationFull) GetItems() []*RelayItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RelayDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"` // UUID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayDevice) Reset() {
	*x = RelayDevice{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayDevice) ProtoMessage() {}

func (x *RelayDevice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayDevice.ProtoReflect.Descriptor instead.
func (*RelayDevice) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{18}
}

func (x *RelayDevice) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *RelayDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RelayItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StationId         string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"` // UUID
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type              string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	DeviceName        string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StatusChangedAtMs int64                  `protobuf:"varint,6,opt,name=status_changed_at_ms,json=statusChangedAtMs,proto3" json:"status_changed_at_ms,omitempty"`
	Available         bool                   `protobuf:"varint,7,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RelayItem) Reset() {
	*x = RelayItem{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayItem) ProtoMessage() {}

func (x *RelayItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayItem.ProtoReflect.Descriptor instead.
func (*RelayItem) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{19}
}

func (x *RelayItem) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *RelayItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RelayItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RelayItem) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *RelayItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RelayItem) GetStatusChangedAtMs() int64 {
	if x != nil {
		return x.StatusChangedAtMs
	}
	return 0
}

func (x *RelayItem) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type RelayDeviceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // UUID
	StationId     string                 `protobuf:"bytes,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"` // UUID
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayDeviceRecord) Reset() {
	*x = RelayDeviceRecord{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayDeviceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayDeviceRecord) ProtoMessage() {}

func (x *RelayDeviceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayDeviceRecord.ProtoReflect.Descriptor instead.
func (*RelayDeviceRecord) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{20}
}

func (x *RelayDeviceRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RelayDeviceRecord) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *RelayDeviceRecord) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *RelayDeviceRecord) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// RelayConfigBatch 配置同步批次：全量或增量配置变更。
// 全量同步时，entries 包含所有站点/设备/item 的快照。
// 增量同步时，entries 包含单个变更事件。
type RelayConfigBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullSync      bool                   `protobuf:"varint,1,opt,name=full_sync,json=fullSync,proto3" json:"full_sync,omitempty"`               // true=全量同步, false=增量变更
	Stations      []*RelayStationFull    `protobuf:"bytes,2,rep,name=stations,proto3" json:"stations,omitempty"`                                // 全量：所有站点
	DeviceRecords []*RelayDeviceRecord   `protobuf:"bytes,3,rep,name=device_records,json=deviceRecords,proto3" json:"device_records,omitempty"` // 全量：所有设备记录
	Events        []*RelayConfigEvent    `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`                                    // 增量：配置变更事件列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayConfigBatch) Reset() {
	*x = RelayConfigBatch{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayConfigBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayConfigBatch) ProtoMessage() {}

func (x *RelayConfigBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayConfigBatch.ProtoReflect.Descriptor instead.
func (*RelayConfigBatch) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{21}
}

func (x *RelayConfigBatch) GetFullSync() bool {
	if x != nil {
		return x.FullSync
	}
	return false
}

func (x *RelayConfigBatch) GetStations() []*RelayStationFull {
	if x != nil {
		return x.Stations
	}
	return nil
}

func (x *RelayConfigBatch) GetDeviceRecords() []*RelayDeviceRecord {
	if x != nil {
		return x.DeviceRecords
	}
	return nil
}

func (x *RelayConfigBatch) GetEvents() []*RelayConfigEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// RelayConfigEvent 单个配置变更事件。
type RelayConfigEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // 事件类型，对应 v1 的 kMsg* 常量
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON 编码的事件体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayConfigEvent) Reset() {
	*x = RelayConfigEvent{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayConfigEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayConfigEvent) ProtoMessage() {}

func (x *RelayConfigEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayConfigEvent.ProtoReflect.Descriptor instead.
func (*RelayConfigEvent) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{22}
}

func (x *RelayConfigEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RelayConfigEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// RelayAvailableItems 可用 item 列表，按站点分组。
type RelayAvailableItems struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Stations      map[string]*RelayAvailableItemList `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map[stationUUID]items
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayAvailableItems) Reset() {
	*x = RelayAvailableItems{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayAvailableItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayAvailableItems) ProtoMessage() {}

func (x *RelayAvailableItems) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayAvailableItems.ProtoReflect.Descriptor instead.
func (*RelayAvailableItems) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{23}
}

func (x *RelayAvailableItems) GetStations() map[string]*RelayAvailableItemList {
	if x != nil {
		return x.Stations
	}
	return nil
}

type RelayAvailableItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemNames     []string               `protobuf:"bytes,1,rep,name=item_names,json=itemNames,proto3" json:"item_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayAvailableItemList) Reset() {
	*x = RelayAvailableItemList{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayAvailableItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayAvailableItemList) ProtoMessage() {}

func (x *RelayAvailableItemList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayAvailableItemList.ProtoReflect.Descriptor instead.
func (*RelayAvailableItemList) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{24}
}

func (x *RelayAvailableItemList) GetItemNames() []string {
	if x != nil {
		return x.ItemNames
	}
	return nil
}

// RelayItemsLatest 多站点的 item 最新时间戳，用于缺失数据查询。
type RelayItemsLatest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Stations      map[string]*ItemsLatest `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map[stationUUID]ItemsLatest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayItemsLatest) Reset() {
	*x = RelayItemsLatest{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayItemsLatest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayItemsLatest) ProtoMessage() {}

func (x *RelayItemsLatest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayItemsLatest.ProtoReflect.Descriptor instead.
func (*RelayItemsLatest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{25}
}

func (x *RelayItemsLatest) GetStations() map[string]*ItemsLatest {
	if x != nil {
		return x.Stations
	}
	return nil
}

// RelayStatusLatest 多站点的最新状态日志行号。
type RelayStatusLatest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stations      map[string]int64       `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // map[stationUUID]latestRowId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayStatusLatest) Reset() {
	*x = RelayStatusLatest{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStatusLatest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStatusLatest) ProtoMessage() {}

func (x *RelayStatusLatest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStatusLatest.ProtoReflect.Descriptor instead.
func (*RelayStatusLatest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{26}
}

func (x *RelayStatusLatest) GetStations() map[string]int64 {
	if x != nil {
		return x.Stations
	}
	return nil
}

// RelayDataBatch 带站点 ID 的数据批次，用于 server-to-server 数据转发。
type RelayDataBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"` // UUID
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`    // "data", "data_gpio", "MissData"
	Points        []*DataPoint           `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayDataBatch) Reset() {
	*x = RelayDataBatch{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayDataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayDataBatch) ProtoMessage() {}

func (x *RelayDataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayDataBatch.ProtoReflect.Descriptor instead.
func (*RelayDataBatch) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{27}
}

func (x *RelayDataBatch) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *RelayDataBatch) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *RelayDataBatch) GetPoints() []*DataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// RelayStatusEvent 带站点 ID 的状态变更事件，用于 server-to-server 状态转发。
type RelayStatusEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StationId       string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"` // UUID
	Identifier      string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`                // 站点标识
	RowId           int64                  `protobuf:"varint,3,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	ItemName        string                 `protobuf:"bytes,4,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ChangedAtUnixMs int64                  `protobuf:"varint,6,opt,name=changed_at_unix_ms,json=changedAtUnixMs,proto3" json:"changed_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RelayStatusEvent) Reset() {
	*x = RelayStatusEvent{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStatusEvent) ProtoMessage() {}

func (x *RelayStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStatusEvent.ProtoReflect.Descriptor instead.
func (*RelayStatusEvent) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{28}
}

func (x *RelayStatusEvent) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *RelayStatusEvent) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *RelayStatusEvent) GetRowId() int64 {
	if x != nil {
		return x.RowId
	}
	return 0
}

func (x *RelayStatusEvent) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *RelayStatusEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RelayStatusEvent) GetChangedAtUnixMs() int64 {
	if x != nil {
		return x.ChangedAtUnixMs
	}
	return 0
}

// RelayMessage server-to-server (relay) 同步的帧包装。
type RelayMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*RelayMessage_DownstreamHello
	//	*RelayMessage_UpstreamHello
	//	*RelayMessage_ConfigBatch
	//	*RelayMessage_DataBatch
	//	*RelayMessage_StatusEvent
	//	*RelayMessage_AvailableItems
	//	*RelayMessage_StationsItemsLatest
	//	*RelayMessage_StationsStatusLatest
	//	*RelayMessage_Error
	Body          isRelayMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayMessage) Reset() {
	*x = RelayMessage{}
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMessage) ProtoMessage() {}

func (x *RelayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v2_sync_v2_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMessage.ProtoReflect.Descriptor instead.
func (*RelayMessage) Descriptor() ([]byte, []int) {
	return file_proto_sync_v2_sync_v2_proto_rawDescGZIP(), []int{29}
}

func (x *RelayMessage) GetBody() isRelayMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RelayMessage) GetDownstreamHello() *RelayDownstreamHello {
	if x != nil {
		if x, ok := x.Body.(*RelayMessage_DownstreamHello); ok {
			return x.DownstreamHello
		}
	}
	return nil
}

func (x *RelayMessage) GetUpstreamHello() *RelayUpstreamHello {
	if x != nil {
		if x, ok := x.Body.(*RelayMessage_UpstreamHello); ok {
			return x.UpstreamHello
		}
	}
	return nil
}

func (x *RelayMessage) GetConfigBatch() *RelayConfigBatch {
	if x != nil {
		if x, ok := x.Body.(*RelayMessage_ConfigBatch); ok {
			return x.ConfigBatch
		}
	}
	return nil
}

func (x *RelayMessage) GetDataBatch() *RelayDataBatch {
	if x != nil {
		if x, ok := x.Body.(*RelayMessage_DataBatch); ok {
			return x.DataBatch
		}
	}
	return nil
}

func (x *RelayMessage) GetStatusEvent() *RelayStatusEvent {
	if x != nil {
		if x, ok := x.Body.(*RelayMessage_StatusEvent); ok {
			return x.StatusEvent
		}
	}
	return nil
}

func (x *RelayMessage) GetAvailableItems() *RelayAvailableItems {
	if x != nil {
		if x, ok := x.Body.(*RelayMessage_AvailableItems); ok {
			return x.AvailableItems
		}
	}
	return nil
}

func (x *RelayMessage) GetStationsItemsLatest() *RelayItemsLatest {
	if x != nil {
		if x, ok := x.Body.(*RelayMessage_StationsItemsLatest); ok {
			return x.StationsItemsLatest
		}
	}
	return nil
}

func (x *RelayMessage) GetStationsStatusLatest() *RelayStatusLatest {
	if x != nil {
		if x, ok := x.Body.(*RelayMessage_StationsStatusLatest); ok {
			return x.StationsStatusLatest
		}
	}
	return nil
}

func (x *RelayMessage) GetError() *ErrorFrame {
	if x != nil {
		if x, ok := x.Body.(*RelayMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRelayMessage_Body interface {
	isRelayMessage_Body()
}

type RelayMessage_DownstreamHello struct {
	DownstreamHello *RelayDownstreamHello `protobuf:"bytes,1,opt,name=downstream_hello,json=downstreamHello,proto3,oneof"`
}

type RelayMessage_UpstreamHello struct {
	UpstreamHello *RelayUpstreamHello `protobuf:"bytes,2,opt,name=upstream_hello,json=upstreamHello,proto3,oneof"`
}

type RelayMessage_ConfigBatch struct {
	ConfigBatch *RelayConfigBatch `protobuf:"bytes,3,opt,name=config_batch,json=configBatch,proto3,oneof"`
}

type RelayMessage_DataBatch struct {
	DataBatch *RelayDataBatch `protobuf:"bytes,4,opt,name=data_batch,json=dataBatch,proto3,oneof"`
}

type RelayMessage_StatusEvent struct {
	StatusEvent *RelayStatusEvent `protobuf:"bytes,5,opt,name=status_event,json=statusEvent,proto3,oneof"`
}

type RelayMessage_AvailableItems struct {
	AvailableItems *RelayAvailableItems `protobuf:"bytes,6,opt,name=available_items,json=availableItems,proto3,oneof"`
}

type RelayMessage_StationsItemsLatest struct {
	StationsItemsLatest *RelayItemsLatest `protobuf:"bytes,7,opt,name=stations_items_latest,json=stationsItemsLatest,proto3,oneof"`
}

type RelayMessage_StationsStatusLatest struct {
	StationsStatusLatest *RelayStatusLatest `protobuf:"bytes,8,opt,name=stations_status_latest,json=stationsStatusLatest,proto3,oneof"`
}

type RelayMessage_Error struct {
	Error *ErrorFrame `protobuf:"bytes,9,opt,name=error,proto3,oneof"`
}

func (*RelayMessage_DownstreamHello) isRelayMessage_Body() {}

func (*RelayMessage_UpstreamHello) isRelayMessage_Body() {}

func (*RelayMessage_ConfigBatch) isRelayMessage_Body() {}

func (*RelayMessage_DataBatch) isRelayMessage_Body() {}

func (*RelayMessage_StatusEvent) isRelayMessage_Body() {}

func (*RelayMessage_AvailableItems) isRelayMessage_Body() {}

func (*RelayMessage_StationsItemsLatest) isRelayMessage_Body() {}

func (*RelayMessage_StationsStatusLatest) isRelayMessage_Body() {}

func (*RelayMessage_Error) isRelayMessage_Body() {}

var File_proto_sync_v2_sync_v2_proto protoreflect.FileDescriptor

const file_proto_sync_v2_sync_v2_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/sync/v2/sync_v2.proto\x12\ftide.sync.v2\"g\n" +
	"\vClientHello\x12-\n" +
	"\x12station_identifier\x18\x01 \x01(\tR\x11stationIdentifier\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\"4\n" +
	"\vServerHello\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\"\x83\x01\n" +
	"\vDeviceItems\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.tide.sync.v2.DeviceItems.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x01\n" +
	"\vStationInfo\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12@\n" +
	"\adevices\x18\x02 \x03(\v2&.tide.sync.v2.StationInfo.DevicesEntryR\adevices\x12\x18\n" +
	"\acameras\x18\x03 \x03(\tR\acameras\x1aU\n" +
	"\fDevicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.tide.sync.v2.DeviceItemsR\x05value:\x028\x01\"\xa1\x01\n" +
	"\vItemsLatest\x12Q\n" +
	"\x0elatest_unix_ms\x18\x01 \x03(\v2+.tide.sync.v2.ItemsLatest.LatestUnixMsEntryR\flatestUnixMs\x1a?\n" +
	"\x11LatestUnixMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"2\n" +
	"\fStatusLatest\x12\"\n" +
	"\rlatest_row_id\x18\x01 \x01(\x03R\vlatestRowId\"\x83\x01\n" +
	"\tDataPoint\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x17\n" +
	"\aunix_ms\x18\x03 \x01(\x03R\x06unixMs\x12*\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x16.tide.sync.v2.DataKindR\x04kind\"T\n" +
	"\tDataBatch\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12/\n" +
	"\x06points\x18\x02 \x03(\v2\x17.tide.sync.v2.DataPointR\x06points\"\x88\x01\n" +
	"\rItemStatusLog\x12\x15\n" +
	"\x06row_id\x18\x01 \x01(\x03R\x05rowId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12+\n" +
	"\x12changed_at_unix_ms\x18\x04 \x01(\x03R\x0fchangedAtUnixMs\"Z\n" +
	"\x0fItemStatusBatch\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12/\n" +
	"\x04logs\x18\x02 \x03(\v2\x1b.tide.sync.v2.ItemStatusLogR\x04logs\"?\n" +
	"\tRpiStatus\x12\x19\n" +
	"\bcpu_temp\x18\x01 \x01(\x01R\acpuTemp\x12\x17\n" +
	"\aunix_ms\x18\x02 \x01(\x03R\x06unixMs\"8\n" +
	"\x15CameraSnapshotRequest\x12\x1f\n" +
	"\vcamera_name\x18\x01 \x01(\tR\n" +
	"cameraName\"B\n" +
	"\x16CameraSnapshotResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"X\n" +
	"\n" +
	"ErrorFrame\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\x8f\x06\n" +
	"\x0eStationMessage\x12>\n" +
	"\fclient_hello\x18\x01 \x01(\v2\x19.tide.sync.v2.ClientHelloH\x00R\vclientHello\x12>\n" +
	"\fserver_hello\x18\x02 \x01(\v2\x19.tide.sync.v2.ServerHelloH\x00R\vserverHello\x12>\n" +
	"\fstation_info\x18\x03 \x01(\v2\x19.tide.sync.v2.StationInfoH\x00R\vstationInfo\x12>\n" +
	"\fitems_latest\x18\x04 \x01(\v2\x19.tide.sync.v2.ItemsLatestH\x00R\vitemsLatest\x12A\n" +
	"\rstatus_latest\x18\x05 \x01(\v2\x1a.tide.sync.v2.StatusLatestH\x00R\fstatusLatest\x128\n" +
	"\n" +
	"data_batch\x18\x06 \x01(\v2\x17.tide.sync.v2.DataBatchH\x00R\tdataBatch\x12K\n" +
	"\x11item_status_batch\x18\a \x01(\v2\x1d.tide.sync.v2.ItemStatusBatchH\x00R\x0fitemStatusBatch\x128\n" +
	"\n" +
	"rpi_status\x18\b \x01(\v2\x17.tide.sync.v2.RpiStatusH\x00R\trpiStatus\x12]\n" +
	"\x17camera_snapshot_request\x18\t \x01(\v2#.tide.sync.v2.CameraSnapshotRequestH\x00R\x15cameraSnapshotRequest\x12`\n" +
	"\x18camera_snapshot_response\x18\n" +
	" \x01(\v2$.tide.sync.v2.CameraSnapshotResponseH\x00R\x16cameraSnapshotResponse\x120\n" +
	"\x05error\x18\v \x01(\v2\x18.tide.sync.v2.ErrorFrameH\x00R\x05errorB\x06\n" +
	"\x04body\"]\n" +
	"\x14RelayDownstreamHello\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\";\n" +
	"\x12RelayUpstreamHello\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\"\x88\x03\n" +
	"\x10RelayStationFull\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\aip_addr\x18\x04 \x01(\tR\x06ipAddr\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\fR\blocation\x12\x18\n" +
	"\apartner\x18\x06 \x01(\fR\apartner\x12\x18\n" +
	"\acameras\x18\a \x01(\fR\acameras\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12/\n" +
	"\x14status_changed_at_ms\x18\t \x01(\x03R\x11statusChangedAtMs\x12\x1a\n" +
	"\bupstream\x18\n" +
	" \x01(\bR\bupstream\x123\n" +
	"\adevices\x18\v \x03(\v2\x19.tide.sync.v2.RelayDeviceR\adevices\x12-\n" +
	"\x05items\x18\f \x03(\v2\x17.tide.sync.v2.RelayItemR\x05items\"@\n" +
	"\vRelayDevice\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xda\x01\n" +
	"\tRelayItem\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12/\n" +
	"\x14status_changed_at_ms\x18\x06 \x01(\x03R\x11statusChangedAtMs\x12\x1c\n" +
	"\tavailable\x18\a \x01(\bR\tavailable\"{\n" +
	"\x11RelayDeviceRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\tR\tstationId\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\"\xeb\x01\n" +
	"\x10RelayConfigBatch\x12\x1b\n" +
	"\tfull_sync\x18\x01 \x01(\bR\bfullSync\x12:\n" +
	"\bstations\x18\x02 \x03(\v2\x1e.tide.sync.v2.RelayStationFullR\bstations\x12F\n" +
	"\x0edevice_records\x18\x03 \x03(\v2\x1f.tide.sync.v2.RelayDeviceRecordR\rdeviceRecords\x126\n" +
	"\x06events\x18\x04 \x03(\v2\x1e.tide.sync.v2.RelayConfigEventR\x06events\"@\n" +
	"\x10RelayConfigEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xc5\x01\n" +
	"\x13RelayAvailableItems\x12K\n" +
	"\bstations\x18\x01 \x03(\v2/.tide.sync.v2.RelayAvailableItems.StationsEntryR\bstations\x1aa\n" +
	"\rStationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.tide.sync.v2.RelayAvailableItemListR\x05value:\x028\x01\"7\n" +
	"\x16RelayAvailableItemList\x12\x1d\n" +
	"\n" +
	"item_names\x18\x01 \x03(\tR\titemNames\"\xb4\x01\n" +
	"\x10RelayItemsLatest\x12H\n" +
	"\bstations\x18\x01 \x03(\v2,.tide.sync.v2.RelayItemsLatest.StationsEntryR\bstations\x1aV\n" +
	"\rStationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.tide.sync.v2.ItemsLatestR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x11RelayStatusLatest\x12I\n" +
	"\bstations\x18\x01 \x03(\v2-.tide.sync.v2.RelayStatusLatest.StationsEntryR\bstations\x1a;\n" +
	"\rStationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"}\n" +
	"\x0eRelayDataBatch\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12/\n" +
	"\x06points\x18\x03 \x03(\v2\x17.tide.sync.v2.DataPointR\x06points\"\xca\x01\n" +
	"\x10RelayStatusEvent\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x15\n" +
	"\x06row_id\x18\x03 \x01(\x03R\x05rowId\x12\x1b\n" +
	"\titem_name\x18\x04 \x01(\tR\bitemName\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12+\n" +
	"\x12changed_at_unix_ms\x18\x06 \x01(\x03R\x0fchangedAtUnixMs\"\xaa\x05\n" +
	"\fRelayMessage\x12O\n" +
	"\x10downstream_hello\x18\x01 \x01(\v2\".tide.sync.v2.RelayDownstreamHelloH\x00R\x0fdownstreamHello\x12I\n" +
	"\x0eupstream_hello\x18\x02 \x01(\v2 .tide.sync.v2.RelayUpstreamHelloH\x00R\rupstreamHello\x12C\n" +
	"\fconfig_batch\x18\x03 \x01(\v2\x1e.tide.sync.v2.RelayConfigBatchH\x00R\vconfigBatch\x12=\n" +
	"\n" +
	"data_batch\x18\x04 \x01(\v2\x1c.tide.sync.v2.RelayDataBatchH\x00R\tdataBatch\x12C\n" +
	"\fstatus_event\x18\x05 \x01(\v2\x1e.tide.sync.v2.RelayStatusEventH\x00R\vstatusEvent\x12L\n" +
	"\x0favailable_items\x18\x06 \x01(\v2!.tide.sync.v2.RelayAvailableItemsH\x00R\x0eavailableItems\x12T\n" +
	"\x15stations_items_latest\x18\a \x01(\v2\x1e.tide.sync.v2.RelayItemsLatestH\x00R\x13stationsItemsLatest\x12W\n" +
	"\x16stations_status_latest\x18\b \x01(\v2\x1f.tide.sync.v2.RelayStatusLatestH\x00R\x14stationsStatusLatest\x120\n" +
	"\x05error\x18\t \x01(\v2\x18.tide.sync.v2.ErrorFrameH\x00R\x05errorB\x06\n" +
	"\x04body*O\n" +
	"\bDataKind\x12\x19\n" +
	"\x15DATA_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DATA_KIND_NORMAL\x10\x01\x12\x12\n" +
	"\x0eDATA_KIND_GPIO\x10\x022e\n" +
	"\x12StationSyncService\x12O\n" +
	"\rStreamStation\x12\x1c.tide.sync.v2.StationMessage\x1a\x1c.tide.sync.v2.StationMessage(\x010\x012]\n" +
	"\x10RelaySyncService\x12I\n" +
	"\vStreamRelay\x12\x1a.tide.sync.v2.RelayMessage\x1a\x1a.tide.sync.v2.RelayMessage(\x010\x01B!Z\x1ftide/pkg/pb/syncproto;syncprotob\x06proto3"

var (
	file_proto_sync_v2_sync_v2_proto_rawDescOnce sync.Once
	file_proto_sync_v2_sync_v2_proto_rawDescData []byte
)

func file_proto_sync_v2_sync_v2_proto_rawDescGZIP() []byte {
	file_proto_sync_v2_sync_v2_proto_rawDescOnce.Do(func() {
		file_proto_sync_v2_sync_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sync_v2_sync_v2_proto_rawDesc), len(file_proto_sync_v2_sync_v2_proto_rawDesc)))
	})
	return file_proto_sync_v2_sync_v2_proto_rawDescData
}

var file_proto_sync_v2_sync_v2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sync_v2_sync_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_sync_v2_sync_v2_proto_goTypes = []any{
	(DataKind)(0),                  // 0: tide.sync.v2.DataKind
	(*ClientHello)(nil),            // 1: tide.sync.v2.ClientHello
	(*ServerHello)(nil),            // 2: tide.sync.v2.ServerHello
	(*DeviceItems)(nil),            // 3: tide.sync.v2.DeviceItems
	(*StationInfo)(nil),            // 4: tide.sync.v2.StationInfo
	(*ItemsLatest)(nil),            // 5: tide.sync.v2.ItemsLatest
	(*StatusLatest)(nil),           // 6: tide.sync.v2.StatusLatest
	(*DataPoint)(nil),              // 7: tide.sync.v2.DataPoint
	(*DataBatch)(nil),              // 8: tide.sync.v2.DataBatch
	(*ItemStatusLog)(nil),          // 9: tide.sync.v2.ItemStatusLog
	(*ItemStatusBatch)(nil),        // 10: tide.sync.v2.ItemStatusBatch
	(*RpiStatus)(nil),              // 11: tide.sync.v2.RpiStatus
	(*CameraSnapshotRequest)(nil),  // 12: tide.sync.v2.CameraSnapshotRequest
	(*CameraSnapshotResponse)(nil), // 13: tide.sync.v2.CameraSnapshotResponse
	(*ErrorFrame)(nil),             // 14: tide.sync.v2.ErrorFrame
	(*StationMessage)(nil),         // 15: tide.sync.v2.StationMessage
	(*RelayDownstreamHello)(nil),   // 16: tide.sync.v2.RelayDownstreamHello
	(*RelayUpstreamHello)(nil),     // 17: tide.sync.v2.RelayUpstreamHello
	(*RelayStationFull)(nil),       // 18: tide.sync.v2.RelayStationFull
	(*RelayDevice)(nil),            // 19: tide.sync.v2.RelayDevice
	(*RelayItem)(nil),              // 20: tide.sync.v2.RelayItem
	(*RelayDeviceRecord)(nil),      // 21: tide.sync.v2.RelayDeviceRecord
	(*RelayConfigBatch)(nil),       // 22: tide.sync.v2.RelayConfigBatch
	(*RelayConfigEvent)(nil),       // 23: tide.sync.v2.RelayConfigEvent
	(*RelayAvailableItems)(nil),    // 24: tide.sync.v2.RelayAvailableItems
	(*RelayAvailableItemList)(nil), // 25: tide.sync.v2.RelayAvailableItemList
	(*RelayItemsLatest)(nil),       // 26: tide.sync.v2.RelayItemsLatest
	(*RelayStatusLatest)(nil),      // 27: tide.sync.v2.RelayStatusLatest
	(*RelayDataBatch)(nil),         // 28: tide.sync.v2.RelayDataBatch
	(*RelayStatusEvent)(nil),       // 29: tide.sync.v2.RelayStatusEvent
	(*RelayMessage)(nil),           // 30: tide.sync.v2.RelayMessage
	nil,                            // 31: tide.sync.v2.DeviceItems.ItemsEntry
	nil,                            // 32: tide.sync.v2.StationInfo.DevicesEntry
	nil,                            // 33: tide.sync.v2.ItemsLatest.LatestUnixMsEntry
	nil,                            // 34: tide.sync.v2.RelayAvailableItems.StationsEntry
	nil,                            // 35: tide.sync.v2.RelayItemsLatest.StationsEntry
	nil,                            // 36: tide.sync.v2.RelayStatusLatest.StationsEntry
}
var file_proto_sync_v2_sync_v2_proto_depIdxs = []int32{
	31, // 0: tide.sync.v2.DeviceItems.items:type_name -> tide.sync.v2.DeviceItems.ItemsEntry
	32, // 1: tide.sync.v2.StationInfo.devices:type_name -> tide.sync.v2.StationInfo.DevicesEntry
	33, // 2: tide.sync.v2.ItemsLatest.latest_unix_ms:type_name -> tide.sync.v2.ItemsLatest.LatestUnixMsEntry
	0,  // 3: tide.sync.v2.DataPoint.kind:type_name -> tide.sync.v2.DataKind
	7,  // 4: tide.sync.v2.DataBatch.points:type_name -> tide.sync.v2.DataPoint
	9,  // 5: tide.sync.v2.ItemStatusBatch.logs:type_name -> tide.sync.v2.ItemStatusLog
	1,  // 6: tide.sync.v2.StationMessage.client_hello:type_name -> tide.sync.v2.ClientHello
	2,  // 7: tide.sync.v2.StationMessage.server_hello:type_name -> tide.sync.v2.ServerHello
	4,  // 8: tide.sync.v2.StationMessage.station_info:type_name -> tide.sync.v2.StationInfo
	5,  // 9: tide.sync.v2.StationMessage.items_latest:type_name -> tide.sync.v2.ItemsLatest
	6,  // 10: tide.sync.v2.StationMessage.status_latest:type_name -> tide.sync.v2.StatusLatest
	8,  // 11: tide.sync.v2.StationMessage.data_batch:type_name -> tide.sync.v2.DataBatch
	10, // 12: tide.sync.v2.StationMessage.item_status_batch:type_name -> tide.sync.v2.ItemStatusBatch
	11, // 13: tide.sync.v2.StationMessage.rpi_status:type_name -> tide.sync.v2.RpiStatus
	12, // 14: tide.sync.v2.StationMessage.camera_snapshot_request:type_name -> tide.sync.v2.CameraSnapshotRequest
	13, // 15: tide.sync.v2.StationMessage.camera_snapshot_response:type_name -> tide.sync.v2.CameraSnapshotResponse
	14, // 16: tide.sync.v2.StationMessage.error:type_name -> tide.sync.v2.ErrorFrame
	19, // 17: tide.sync.v2.RelayStationFull.devices:type_name -> tide.sync.v2.RelayDevice
	20, // 18: tide.sync.v2.RelayStationFull.items:type_name -> tide.sync.v2.RelayItem
	18, // 19: tide.sync.v2.RelayConfigBatch.stations:type_name -> tide.sync.v2.RelayStationFull
	21, // 20: tide.sync.v2.RelayConfigBatch.device_records:type_name -> tide.sync.v2.RelayDeviceRecord
	23, // 21: tide.sync.v2.RelayConfigBatch.events:type_name -> tide.sync.v2.RelayConfigEvent
	34, // 22: tide.sync.v2.RelayAvailableItems.stations:type_name -> tide.sync.v2.RelayAvailableItems.StationsEntry
	35, // 23: tide.sync.v2.RelayItemsLatest.stations:type_name -> tide.sync.v2.RelayItemsLatest.StationsEntry
	36, // 24: tide.sync.v2.RelayStatusLatest.stations:type_name -> tide.sync.v2.RelayStatusLatest.StationsEntry
	7,  // 25: tide.sync.v2.RelayDataBatch.points:type_name -> tide.sync.v2.DataPoint
	16, // 26: tide.sync.v2.RelayMessage.downstream_hello:type_name -> tide.sync.v2.RelayDownstreamHello
	17, // 27: tide.sync.v2.RelayMessage.upstream_hello:type_name -> tide.sync.v2.RelayUpstreamHello
	22, // 28: tide.sync.v2.RelayMessage.config_batch:type_name -> tide.sync.v2.RelayConfigBatch
	28, // 29: tide.sync.v2.RelayMessage.data_batch:type_name -> tide.sync.v2.RelayDataBatch
	29, // 30: tide.sync.v2.RelayMessage.status_event:type_name -> tide.sync.v2.RelayStatusEvent
	24, // 31: tide.sync.v2.RelayMessage.available_items:type_name -> tide.sync.v2.RelayAvailableItems
	26, // 32: tide.sync.v2.RelayMessage.stations_items_latest:type_name -> tide.sync.v2.RelayItemsLatest
	27, // 33: tide.sync.v2.RelayMessage.stations_status_latest:type_name -> tide.sync.v2.RelayStatusLatest
	14, // 34: tide.sync.v2.RelayMessage.error:type_name -> tide.sync.v2.ErrorFrame
	3,  // 35: tide.sync.v2.StationInfo.DevicesEntry.value:type_name -> tide.sync.v2.DeviceItems
	25, // 36: tide.sync.v2.RelayAvailableItems.StationsEntry.value:type_name -> tide.sync.v2.RelayAvailableItemList
	5,  // 37: tide.sync.v2.RelayItemsLatest.StationsEntry.value:type_name -> tide.sync.v2.ItemsLatest
	15, // 38: tide.sync.v2.StationSyncService.StreamStation:input_type -> tide.sync.v2.StationMessage
	30, // 39: tide.sync.v2.RelaySyncService.StreamRelay:input_type -> tide.sync.v2.RelayMessage
	15, // 40: tide.sync.v2.StationSyncService.StreamStation:output_type -> tide.sync.v2.StationMessage
	30, // 41: tide.sync.v2.RelaySyncService.StreamRelay:output_type -> tide.sync.v2.RelayMessage
	40, // [40:42] is the sub-list for method output_type
	38, // [38:40] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_proto_sync_v2_sync_v2_proto_init() }
func file_proto_sync_v2_sync_v2_proto_init() {
	if File_proto_sync_v2_sync_v2_proto != nil {
		return
	}
	file_proto_sync_v2_sync_v2_proto_msgTypes[14].OneofWrappers = []any{
		(*StationMessage_ClientHello)(nil),
		(*StationMessage_ServerHello)(nil),
		(*StationMessage_StationInfo)(nil),
		(*StationMessage_ItemsLatest)(nil),
		(*StationMessage_StatusLatest)(nil),
		(*StationMessage_DataBatch)(nil),
		(*StationMessage_ItemStatusBatch)(nil),
		(*StationMessage_RpiStatus)(nil),
		(*StationMessage_CameraSnapshotRequest)(nil),
		(*StationMessage_CameraSnapshotResponse)(nil),
		(*StationMessage_Error)(nil),
	}
	file_proto_sync_v2_sync_v2_proto_msgTypes[29].OneofWrappers = []any{
		(*RelayMessage_DownstreamHello)(nil),
		(*RelayMessage_UpstreamHello)(nil),
		(*RelayMessage_ConfigBatch)(nil),
		(*RelayMessage_DataBatch)(nil),
		(*RelayMessage_StatusEvent)(nil),
		(*RelayMessage_AvailableItems)(nil),
		(*RelayMessage_StationsItemsLatest)(nil),
		(*RelayMessage_StationsStatusLatest)(nil),
		(*RelayMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sync_v2_sync_v2_proto_rawDesc), len(file_proto_sync_v2_sync_v2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_sync_v2_sync_v2_proto_goTypes,
		DependencyIndexes: file_proto_sync_v2_sync_v2_proto_depIdxs,
		EnumInfos:         file_proto_sync_v2_sync_v2_proto_enumTypes,
		MessageInfos:      file_proto_sync_v2_sync_v2_proto_msgTypes,
	}.Build()
	File_proto_sync_v2_sync_v2_proto = out.File
	file_proto_sync_v2_sync_v2_proto_goTypes = nil
	file_proto_sync_v2_sync_v2_proto_depIdxs = nil
}
